### ISSUE TITLE
Does not get compiled

### ISSUE THREAD

**Issue by farbodshn** [HongjianLi/idock#10]
Hi, I'm new to compiling softwares and when I want to use the "make" command it shows me this:

clang++ -O2 -o obj/safe_counter.o src/safe_counter.cpp -c -std=c++11 -Wall -Wno-unused-local-typedef -
clang: error: -E or -x required when input is from standard input
clang: error: cannot specify -o when generating multiple output files
make: *** [obj/safe_counter.o] Error 1

I have installed boost libraries from synaptic, but I couldn't install the latest version through compiling. Can you help me?

**Comment by HongjianLi** [comment]
You are recommended to use the prebuilt executables in the bin directory.
Download the latest version of idock at https://github.com/HongjianLi/idock/releases

**Comment by farbodshn** [comment]
Thanks :)
