### ISSUE TITLE
log.csv is not ordered and skips elements

### ISSUE THREAD

**Issue by tobigithub** [HongjianLi/idock#5]
Hi,
this is for idock exe 2.3.1, for large screening sets, the order of compounds in the log.scv is sorted, but more severe, those compounds without score are not listed anymore.

Issues here derive from the conversion pipeline, that goes for example from SDF-->PDBQT hence, molconvert and openbabel to autodocktools and others forth and back. Usually large compound lists are held in DBs and then sorted in Spreadsheets. Its easier to synchronize large lists if all compounds are in. 

That means the original compound list can not be easily synchronized with the docking output, meaning one could just copy/paste the docking energies to the right new columns in an EXCEL sheet. Instead a more complex vlookup function has to be written.

Solution for user: Split the output with tee.exe or pipe results into a separate log file:
idock.exe --conf idock.conf | tee -a output-log.txt

Fix for the program: allow for complete and ordered output of all docking results (even unsuccessful ones) similar to screen output. Hence 100 compounds in, 100 results in the csv.log. The ordered output option in the CSV file is preferred because the piping to an output log has issues with correctly formatting the numbers (sometimes spaces between numbers are missing, see next issue).

Tobias

**Comment by HongjianLi** [comment]
Hi Tobias Kind,
  I have just released idock v2.1.4, which incorporates your comments and output even unsuccessfully docked results to the log file in csv format. Now that you can just copy and paste the docking energy values to the right new columns in an Excel sheet. Try out this new minor version and see if it fits your purpose. https://github.com/HongjianLi/idock/archive/v2.1.4.tar.gz

**Comment by tobigithub** [comment]
Hi,
thanks alot, much appreciated, I just downloaded the binaries and did some 
consistency checks, the energy values are off for some values (R2= 0.96) 
but this is related to the random tree as I understand and the different 
conformers. Other than that it performs well. Also drag-drop works well.
Cheers
Tobias


> Hi Tobias Kind,
>   I have just released idock v2.1.4, which incorporates your comments 
and
> output even unsuccessfully docked results to the log file in csv format.
> Now that you can just copy and paste the docking energy values to the 
right
> new columns in an Excel sheet. Try out this new minor version and see if 
it
> fits your purpose.
> https://github.com/HongjianLi/idock/archive/v2.1.4.tar.gz
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/HongjianLi/idock/issues/5#issuecomment-72354864

Dr. Tobias Kind
UC Davis Genome Center
Metabolomics Group

http://genomecenter.ucdavis.edu
Tel:+1-530-752-9922

**Comment by tobigithub** [comment]
Perfect,
just downloaded it. Thank you.
Tobias
