### ISSUE TITLE
unrecognised option 'ligand_folder'

### ISSUE THREAD

**Issue by tobigithub** [HongjianLi/idock#8]
Hi,
the example files from the binary distro 2.1.4 all work, the ones in the current repo all have
ligand_folder = ../../../ligands/ANP
which leads to
unrecognised option 'ligand_folder'

Solution: 
replace
ligand_folder = ../../../ligands/ANP
with
input_folder = ../../../ligands/ANP

I also noticed that some of the examples from the master-branch and the binary distro are different.
Cheers
Tobias

**Comment by HongjianLi** [comment]
Hi,
  The master branch is for developing a brand new version v3.0.0, which supports GPU computing using CUDA/OpenCL. It is currently under development and anything is subject to change. Do not use the master branch at the moment. Instead, the v2.x branch is for stable releases.

**Comment by HongjianLi** [comment]
Hi Tobias,

Now the previous `ligand_folder` and `input_folder` options are changed to `ligand` in conformance of AutoDock Vina, but the `ligand` option of idock allows the user to specify a single ligand file or a folder of ligand files.
